# Generated by Django 6.0.6 on 2026-06-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Narx turi nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Narx turi',
                'verbose_name_plural': 'Narx turlari',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Mahsulot nomi')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Artikul / SKU')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Narxi (so'm)")),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pricetype', verbose_name='Narx turi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot narxi',
                'verbose_name_plural': 'Mahsulot narxlari',
                'unique_together': {('product', 'price_type')},
            },
        ),
    ]
