# Generated by Django 6.0.6 on 2026-06-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='worker_share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name="1 ta non uchun nonvoy xaqi (so'm)"),
        ),
    ]
