# Generated by Django 6.0.6 on 2026-06-10 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.PositiveIntegerField(verbose_name='Rejalashtirilgan miqdor (dona)')),
                ('date', models.DateField(verbose_name='Reja sanasi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=15, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Ishlab chiqarish rejasi',
                'verbose_name_plural': 'Ishlab chiqarish rejalari',
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_quantity', models.PositiveIntegerField(verbose_name="Amalda tayyorlangan (Sog'lom dona)")),
                ('waste_quantity', models.PositiveIntegerField(default=0, verbose_name='Brak / Yaroqsiz (dona)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tizimga kiritilgan vaqt')),
                ('baker', models.ForeignKey(limit_choices_to={'role': 'baker'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul Nonvoy")),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionplan', verbose_name='Asoslangan reja')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Ishlab chiqarish fakti',
                'verbose_name_plural': 'Ishlab chiqarish faktlari',
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name="Tayyor mahsulot qoldig'i (dona)")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': "Tayyor mahsulot qoldig'i",
                'verbose_name_plural': 'Tayyor mahsulot qoldiqlari',
            },
        ),
    ]
