# Generated by Django 6.0.6 on 2026-06-12 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='is_salary_calculated',
            field=models.BooleanField(default=False, verbose_name='Ish haqi hisoblandimi?'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='baker',
            field=models.ForeignKey(limit_choices_to={'is_staff': True, 'role': 'baker'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul Nonvoy"),
        ),
    ]
