# Generated by Django 6.0.6 on 2026-06-17 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionrecord_is_salary_calculated_and_more'),
        ('products', '0002_product_worker_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Qaytarilgan miqdor')),
                ('reason', models.CharField(choices=[('stale', 'Qatib qolgan (Sifatini yoqotgan)'), ('back_to_stock', 'Asosiy omborga qaytarish'), ('gift', 'Ehsan / Hadya')], max_length=20, verbose_name='Qaytarish sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qaytarilgan vaqt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Mahsulot qaytimi',
                'verbose_name_plural': 'Mahsulot qaytimlari',
            },
        ),
        migrations.CreateModel(
            name='SellerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Vitrindagi qoldiq (dona)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot')),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Sotuvchi vitrinasi',
                'verbose_name_plural': 'Sotuvchilar vitrinalari',
                'unique_together': {('seller', 'product')},
            },
        ),
    ]
