# Generated by Django 6.0.6 on 2026-06-21 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productreturn_sellerstock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='baker',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'baker'), ('role', 'admin'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul Nonvoy"),
        ),
        migrations.AlterField(
            model_name='sellerstock',
            name='seller',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'seller'), ('role', 'admin'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi'),
        ),
    ]
