# Generated by Django 6.0.6 on 2026-06-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_productionrecord_baker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionrecord',
            name='plan',
        ),
        migrations.AlterModelOptions(
            name='productionrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ishlab chiqarish fakti', 'verbose_name_plural': 'Ishlab chiqarish faktlari'},
        ),
        migrations.DeleteModel(
            name='ProductionPlan',
        ),
    ]
