# Generated by Django 6.0.6 on 2026-06-10 16:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Mijoz ismi')),
                ('customer_phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Format: +998XXXXXXXXX', regex='^\\+998\\d{9}$')], verbose_name='Mijoz telefoni')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Umumiy summa')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd pul'), ('click', 'Click / Payme'), ('debt', 'Qarzga (Nasiya)')], default='cash', max_length=10, verbose_name="To'lov turi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sotilgan vaqt')),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi (Kassir)')),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdori (dona)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotilgan narxi')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Oraliq summa')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Mahsulot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Sotuv cheki')),
            ],
            options={
                'verbose_name': 'Sotilgan mahsulot',
                'verbose_name_plural': 'Sotilgan mahsulotlar',
            },
        ),
    ]
