# Generated by Django 6.0.6 on 2026-06-17 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_options_alter_sale_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Format: +998YYXXXXXXX', regex='^\\+998\\d{9}$')], verbose_name='Mijoz telefoni'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('debt', 'Qarzga (Nasiya)')], default='cash', max_length=10),
        ),
    ]
