# Generated by Django 6.0.6 on 2026-06-21 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_options_alter_sale_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={},
        ),
        migrations.AddField(
            model_name='sale',
            name='debt_status',
            field=models.CharField(choices=[('paid', 'Yopildi'), ('unpaid', "To'lanmoqda / Faol")], default='paid', max_length=10, verbose_name='Qarz holati'),
        ),
        migrations.AddField(
            model_name='sale',
            name='remaining_debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Qolgan qarz summasi'),
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'langan miqdor")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="To'lov vaqti")),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="Pulni yig'gan xodim")),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to='sales.sale', verbose_name='Qaysi qarz uchun')),
            ],
            options={
                'verbose_name': "Qarz To'lovi",
                'verbose_name_plural': "Qarz To'lovlari",
            },
        ),
    ]
