# Generated by Django 6.0.6 on 2026-06-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (Rahbar)'), ('seller', 'Sotuvchi (Kassir)'), ('baker', 'Nonvoy (Ishlab chiqaruvchi)')], default='admin', max_length=10, verbose_name='Roli'),
        ),
    ]
