# Generated by Django 6.0.6 on 2026-06-17 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998YYXXXXXXX ko'rinishida bo'lishi kerak.", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (Rahbar)'), ('seller', 'Sotuvchi (Kassir)'), ('baker', 'Nonvoy (Ishlab chiqaruvchi)'), ('Omborchi / Menejer', 'Omborchi / Menejer')], default='admin', max_length=25, verbose_name='Roli'),
        ),
    ]
