# Generated by Django 6.0.6 on 2026-06-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phone_number_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (Rahbar)'), ('seller', 'Sotuvchi (Kassir)'), ('baker', 'Nonvoy (Ishlab chiqaruvchi)'), ('manager', 'Omborchi / Menejer')], default='admin', max_length=25, verbose_name='Roli'),
        ),
    ]
