# Generated by Django 6.0.6 on 2026-06-10 14:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Keltirilgan miqdor')),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Qolgan miqdor')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sotib olish narxi (1 birlik uchun)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kirim vaqti')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='recipes.ingredient', verbose_name='Ingredient')),
            ],
            options={
                'verbose_name': 'Xomashyo partiyasi',
                'verbose_name_plural': 'Xomashyo partiyalari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Kirim (Satib olindi)'), ('OUT', 'Chiqim (Ishlab chiqarishga)'), ('WASTE', 'Yaroqsiz (Brak / Isrof)')], max_length=10, verbose_name='Harakat turi')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miqdor')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sabab / Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Harakat vaqti')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ingredientbatch', verbose_name='Tegishli partiya')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='recipes.ingredient', verbose_name='Ingredient')),
            ],
            options={
                'verbose_name': 'Ombor harakati',
                'verbose_name_plural': 'Ombor harakatlari',
            },
        ),
    ]
