# Generated by Django 6.0.6 on 2026-06-10 13:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Ingredient nomi')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramm'), ('litr', 'Litr'), ('dona', 'Dona'), ('gramm', 'Gramm')], default='kg', max_length=10, verbose_name="O'lchov birligi")),
                ('min_limit', models.DecimalField(decimal_places=3, default=Decimal('10.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Minimal qoldiq limiti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ingredient (Xomashyo)',
                'verbose_name_plural': 'Ingredientlar (Xomashyolar)',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tayyorlanish usuli (Tavsif)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='products.product', verbose_name='Tayyor mahsulot')),
            ],
            options={
                'verbose_name': 'Retsept',
                'verbose_name_plural': 'Retseptlar',
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Ketadigan miqdor (1 dona uchun)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.ingredient', verbose_name='Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipes.recipe', verbose_name='Retsept')),
            ],
            options={
                'verbose_name': 'Retsept tarkibiy qismi',
                'verbose_name_plural': 'Retsept tarkiblari',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
