# Generated by Django 6.0.6 on 2026-06-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=255, verbose_name='Telegram Bot Token')),
                ('chat_id', models.CharField(max_length=100, verbose_name='Guruh yoki Kanal ID (Chat ID)')),
                ('alert_low_stock', models.BooleanField(default=True, verbose_name='Xomashyo kam qolganda ogohlantirish?')),
                ('alert_new_debt', models.BooleanField(default=True, verbose_name='Yangi qarz urilganda ogohlantirish?')),
                ('alert_daily_report', models.BooleanField(default=True, verbose_name="Kunlik moliyaviy hisobotni Telegramga jo'natish?")),
                ('is_active', models.BooleanField(default=True, verbose_name='Telegram xizmati faolmi?')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Sozlamasi',
                'verbose_name_plural': 'Telegram Sozlamalari',
            },
        ),
    ]
